# Process Dashboard Configuration

# Display settings
display:
  refresh_rate: 2  # Update interval in seconds
  theme:
    background: "#001100"
    text: "#00FF00"
    accent: "#008800"
    error: "#FF0000"
    warning: "#FFFF00"
    success: "#00FF00"
  columns:
    - pid
    - name
    - cpu_percent
    - memory_percent
    - status
    - user
    - priority
    - group

# Process management
process:
  default_priority: normal
  auto_cleanup: true
  history_size: 1000
  warning_thresholds:
    cpu_percent: 80
    memory_percent: 80
  critical_thresholds:
    cpu_percent: 95
    memory_percent: 95

# Resource management
resources:
  enable_limits: true
  default_limits:
    memory_mb: 1024
    cpu_percent: 50
  check_interval: 5

# SNMP monitoring
snmp:
  enabled: false
  default_port: 161
  community: public
  metrics:
    - cpu_load
    - memory_usage
    - disk_io
    - network_io
  collection_interval: 30

# Process groups
groups:
  system:
    color: "#4444FF"
    priority: high
  user:
    color: "#44FF44"
    priority: normal
  background:
    color: "#888888"
    priority: low

# Logging
logging:
  level: INFO
  file: dashboard.log
  max_size: 10MB
  backup_count: 3
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Keyboard shortcuts
keybindings:
  quit: "q"
  refresh: "r"
  kill_process: "k"
  stop_process: "s"
  resume_process: "c"
  toggle_details: "d"
  toggle_group_view: "g"
  help: "h"
