name: Codex Task Watcher

on:
  push:
    paths:
      - 'CODEX_TASKS.md'
      - 'scripts/assign_to_codex.py'
  workflow_dispatch:

jobs:
  assign-codex-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Codex Task Assignment Script
        run: |
          python3 scripts/assign_to_codex.py
      - name: Commit and push Codex assignments
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: assign new tasks to Codex via watcher"
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
